version: '3'

services:
  app:
    build: .
    container_name: zhavia-app
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: zhavia-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=zhavia-db
      - MYSQL_DATABASE=zhavia-db
      - MYSQL_USER=zhavia
      - MYSQL_PASSWORD=zhavia-password
