version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: zhavia-app
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app:delegated
    depends_on:
      - db
      - elasticsearch

  db:
    image: mariadb:latest
    container_name: zhavia-db
    restart: always
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=zhavia-db
      - MYSQL_DATABASE=zhavia-db
      - MYSQL_USER=zhavia
      - MYSQL_PASSWORD=zhavia-password

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: zhavia-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  dbdata:
  esdata:
