version: '3'

services:
  app:
    build: .
    container_name: zhavia-app
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: zhavia-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=zhavia-db
      - POSTGRES_DB=zhavia-db

  pgadmin:
    image: dpage/pgadmin4
    container_name: zhavia-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8000:80'
    depends_on:
      - db
